### PR TITLE
Edited Sticky Footer and Header Layout

### PR DESCRIPTION
**Pull request by DigitalDesignerOnline**
I apparently did not have the newest version of your repo so my solution didn't work with the repo but did with the dev server, I have rectified the issue and tested the repo by downloading, you are good to go mate.

### CODE REVIEW

**Comment by Logan1x** [comment]
is this pr for this one https://github.com/Logan1x/Logan1x.github.io/issues/28#issuecomment-338567684 ?

**Comment by DigitalDesignerOnline** [comment]
yes it is, I downloaded your repo to do the edits but my fork was not up to date when I sent the last repo, sorry about that. You can test the zip file I uploaded or my fork to verify its working now.

**Comment by Logan1x** [comment]
yes its working fine but need to remove this
screenshot-2017-10-23 khushal sharma
 and replace the facebook and youtube icon with quora and stackoverflow

**Comment by DigitalDesignerOnline** [comment]
so drop the copyright and replace facebook and youtube with quora and stack, on it mate ;)

**Comment by Logan1x** [comment]
and back to top is not working may be beause i am on same page

**Comment by DigitalDesignerOnline** [comment]
ok check it now, I have replaced the icons I will get the back to top scroll effect sorted now for you mate.

**Comment by DigitalDesignerOnline** [comment]
in truth, do you need a back to top icon if your site is now responsive for a full width layout? or is this for within the terminal window?

**Review by Logan1x — APPROVED** [review]

**Comment by DigitalDesignerOnline** [comment]
back to top link added :) works for the terminal window as the rest will stay responsive fullscreen

**Comment by Logan1x** [comment]
screenshot-2017-10-23 khushal sharma 1
too much space between linkedin and twitter icon and stackoverflow link is not working.

**Comment by DigitalDesignerOnline** [comment]
the quora icon should be appearing there, will check it out later  today.

**Comment by Logan1x** [comment]
Ok

**Comment by Logan1x** [comment]
@DigitalDesignerOnline  did you checked what is the issue?

**Pull request merged**
