### PR TITLE
Revert "New Sticky Header, Footer and New Icons added to html and css pages"

### PR DESCRIPTION
**Pull request by Logan1x**
Reverts Logan1x/Logan1x.github.io#32

### CODE REVIEW

**Comment by Logan1x** [comment]
peek 2017-10-23 10-26
this is what i was getiing after merging your pr.

**Comment by Logan1x** [comment]
@DigitalDesignerOnline

**Comment by DigitalDesignerOnline** [comment]
can you ensure cache is cleared as when I view it on my server and the screenshot I sent in the comments on the issue request seem to show differently. I will try to redo the repo and pr and see if I uploaded something incorrectly as well.

**Comment by Logan1x** [comment]
Ok let me check again by cloning your repo and run it locally😅

**Pull request merged**
