### PR TITLE
Website Revision

### PR DESCRIPTION
**Pull request by DigitalDesignerOnline**
I have edited a few pages and removed the unneeded elements I have began adding mobile styling to your page and removed the scrollbar within desktop view. I would be happy to assist further.

### CODE REVIEW

**Comment by Logan1x** [comment]
the website is mobile responsive now but the ternimal looking in web mode is too bad can you make it better or should i revert it ? @DigitalDesignerOnline

**Comment by DigitalDesignerOnline** [comment]
for sure, what did you have in mind mate :) I basically just made sure everything would adjust to mobility, we can surely alter the remaining elements to give you a sweet online presence ;)

**Comment by DigitalDesignerOnline** [comment]
Let me take another stab and I will shoot you a new pull shortly. In the meantime if you have any further visions for your site we can surely integrate them, maybe a lightbox popup of your various portfolio links which could then within have a small case study and a link to the repo on git etc. your thoughts? Basically sky is the limit mate :) It's thanksgiving in Canada so I have the whole weekend to tinker lol

**Comment by Logan1x** [comment]
@DigitalDesignerOnline  you did excellent work for making website mobile responsive But by doing this the web version's terminal width increased so all I want to do is decrease the width and if you can delete the scroll bar in terminal😁 
Just enjoy your thanksgiving for now after then please do it better😊 and **thanks again for contribution.**

**Comment by DigitalDesignerOnline** [comment]
already have it open and tweaking the design further. Happy to assist.

**Comment by DigitalDesignerOnline** [comment]
what was the desktop width you wanted to have it at, currently it is at 1050px for max width, 100% width. I have addressed the scrollbar and went back to a main browser window scroll with the terminal window holding all content visible. I have spaced out the terminal buttons as well as spacing to better match your original as well. Adding the pull for you to check out now.

**Comment by Logan1x** [comment]
i don't know the previous width but it looks like similar to this.
image

**Comment by Logan1x** [comment]
now it's looking like this 
image

**Pull request merged**
