### PR TITLE
Edited spacing and slight layout change

### PR DESCRIPTION
**Pull request by DigitalDesignerOnline**

### CODE REVIEW

**Comment by Logan1x** [comment]
if you can make it like this then it would be ...
image

**Comment by DigitalDesignerOnline** [comment]
how do you want the terminal scroll to be handled for desktop view? By the browser

So end result should have the entire terminal window within the visible screen/window correct? That being said we just need to establish how we will handle the hidden content below the terminal cutoff point?

**Comment by DigitalDesignerOnline** [comment]
take a gander at this, is this better for the layout, now for the content scrolling. :)
http://theonlinelifesaver.com/khushal/

**Comment by Logan1x** [comment]
I am not able to scroll ....it is normal?

**Comment by DigitalDesignerOnline** [comment]
thats what I am asking, how would you like the scrolling to be handled. if we are controlling the height of the terminal box then we would need to have a scrollbar within it for desktop view but you mentioned to remove it so I was wondering what you were wanting instead. Let me know and I will add the scroll functionality as per your request and update the preview. just didn't want to waste a tonne of pulls until its right ;)

**Comment by DigitalDesignerOnline** [comment]
take a peak now and see if this works better for you
http://theonlinelifesaver.com/khushal/

**Comment by Logan1x** [comment]
it's better but width is not fixed yet.

**Comment by Logan1x** [comment]
we'll go with the scroll.

**Comment by DigitalDesignerOnline** [comment]
bot sites are 1050 in width, can you specify what width you would like it to be? the variance you may be seeing is due to a browser scrollbar being there then not as that makes it look like it shifts a bit when comparing but if oyu view with the dev inspect element tool you can compare them to see their dimensions.

**Comment by DigitalDesignerOnline** [comment]
did you want to add styling to the scroll bar?

**Comment by Logan1x** [comment]
I like the first one ...
image

**Comment by DigitalDesignerOnline** [comment]
shoot me the url and i will check it out mate

**Comment by Logan1x** [comment]
http://www.vbforums.com/showthread.php?829809-Custom-scroll-bar-in-vb-net  I just found this image on duckduckgo. if you find this use it  otherwise we'll go with the default one or may you could suggest that gives terminal feeling.

**Comment by DigitalDesignerOnline** [comment]
check out the preview again, I have updated the scrollbar with webkit css styling if you like it I will shoot the pull request over right away.

**Pull request merged**
