### PR TITLE
added hover shading to buttons

### PR DESCRIPTION
**Pull request by ab-gh**
added darker (~+20% black) shading to buttons on window

### CODE REVIEW

**Comment by ab-gh** [comment]
this repo was marked for hacktoberfest, so I thought i'd just make some little tweaks to look nicer

if I have time ill add the over "x", "-" and "+" to the red, yellow and green buttons

**Comment by Logan1x** [comment]
github and linked buttons are not hovering now @electric-blue-green

**Comment by ab-gh** [comment]
they are for me?

**Comment by Logan1x** [comment]
I checked on my friend websites it's working on there too ( On Full HD). So if you know the problem you can help

ezgif-3-3f3befb4b0

and for non only hd screen
screenshot 30

**Pull request merged**
