### PR TITLE
Scrollbar alignment fixed

### PR DESCRIPTION
**Pull request by bharm1**
Fixed screen padding for better alignment. stylesheet.css 127

### CODE REVIEW

**Comment by Logan1x** [comment]
@bharm1  what do you mean by your PR name or it was just random?

**Comment by bharm1** [comment]
Sorry, it was just random.  The scroll bar was misaligned by just a little bit. So what I did was change the padding variable for the scroll bar which aligned it a little better in my opinion.

**Comment by Logan1x** [comment]
For now it's okay but next time when you add any PR make sure you add name relating to pr otherwise it may be closed @bharm1 and thanks for your contribution 🤗

**Comment by Logan1x** [comment]
This website is not mobile friendly can you make it mobile friendly ? @bharm1

**Comment by bharm1** [comment]
Okay thanks for the feedback! I will definitely make sure I do that next time. This was one of my first PRs ever.  As far as making the website mobile, unfortunately I do not have much experience in this as website building is not exactly my field of expertise.

**Comment by Logan1x** [comment]
No problem 😊 @bharm1

**Pull request merged**
